### ISSUE TITLE
点検一覧に検索を付ける(担当予定者で絞り込みたい)

### ISSUE THREAD

**Issue by yamadashizuka** [yamadashizuka/kilogy#20]
ホントはログイン作ってログインした本人のだけが見えるってしたい。
けど、どうせするなら作業者とか管理者とかそのへんのロールも整理したい。
ので、そこらへんまとめて今はパス。
ということで、このIssuは、とりあえず点検一覧を担当予定者で絞り込めればDoneってことで。

**Comment by yada-ITA** [comment]
ついでに点検予定年月の昇順ソートが追加要望にあがったので、
いっしょにやっときます。
