### ISSUE TITLE
controller→modelへのロジック移動（inspections_controller）

### ISSUE THREAD

**Issue by yada-ITA** [yamadashizuka/kilogy#27]
app/controllers/inspections_controller.rbのL77、createInspectionsメソッドのロジックを
modelに持って行った方が良いと思うです。

**Comment by ryo-ryukalice** [comment]
これも拾いますー。

**Comment by yamadashizuka** [comment]
わー。よろしくお願いしますーっ。

**Comment by yada-ITA** [comment]
ありがとうございますー！ :smiley_cat:

**Comment by yada-ITA** [comment]
動作確認Done（masterにもMarge済 #87 ）なので、closeしますー。
