### ISSUE TITLE
点検登録の画面での緯度経度を入力不可にしておきたい

### ISSUE THREAD

**Issue by yamadashizuka** [yamadashizuka/kilogy#34]
テキストフィールドそのままなので、変更できちゃうので、これは見えるだけで入力は不可な感じにしておきたい。

**Comment by ryo-ryukalice** [comment]
これも拾います！

**Comment by yamadashizuka** [comment]
よ、よろしくおねがいしますー。 :sweat_smile:

**Comment by yada-ITA** [comment]
動作確認Done（masterにもMarge済 #81  ）なので、closeしますー。:+1:
