### ISSUE TITLE
問合せの確認画面で表示される登録日/更新日が間違っている

### ISSUE THREAD

**Issue by yamadashizuka** [yamadashizuka/kilogy#76]
問い合わせの確認画面↓
kilogy-test.herokuapp.com/topics/#　　※#はTopicのID
で表示される「更新日」「登録日」の表示元が @topic.flag.created_at と @topic.flag.updated_at になってる。
↓を修正すること！
kilogy/app/views/topics/show.html.erb

**Comment by ryo-ryukalice** [comment]
拾います！

**Comment by yada-ITA** [comment]
:smiley: :sparkles:

**Comment by yamadashizuka** [comment]
@yada-ITA さん、herokuあげて動作確認できたらCloseしてくださいー。

**Comment by yada-ITA** [comment]
りょうかいです～！:+1:

**Comment by yada-ITA** [comment]
動作確認Done（masterにもMarge済 #81 ）なので、closeしますー。
