### ISSUE TITLE
設備(Equipment)に点検(Inspection)が紐づいてても、今年分でなければ点検予定未作成の設備一覧に出るようにしたい

### ISSUE THREAD

**Issue by yamadashizuka** [yamadashizuka/kilogy#9]
/app/controllers/equipment_controller.rb の noInspectionList に書いてある
@equipment = Equipment.includes(:inspection).where(:inspections => { :equipment_id => nil})
をどうにかすればいいんだろうとは思うのだけども……悩み中(汗)

**Comment by yada-ITA** [comment]
その前に…今年の定義が結構曖昧ではありますが…。
いったん、こんな感じでやっときます。

・点検予定年月が、今日の年月よりも1年(12ヶ月)より古いものは、点検予定無しとみなす。
・点検予定年月が、今日の年月から1年以下のものと、未来日付のものは、点検予定ありとみなす。

　例：確認した日が2015年3月12日ならば、
　　　　・点検予定年月が2014年3月以降のものは、点検予定あり。
　　　　・点検予定年月が2014年2月以前のものは、点検予定無し。

**Comment by yamadashizuka** [comment]
はい、とりあえずそれで良いですー。
年に一度の点検ってノリで！
よしなによろしくお願いします。
